server:
  port: 9501

spring:
  application:
    name: zuul-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

zuul:
  routes:
    api-ribbon:
      path: /api-ribbon/**
      serviceId: consumer-ribbon
    consumer-feign:
      path: /api-feign/**
      serviceId: consumer-feign

