server:
  port: 8080

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri:
          search-paths:
          username:
          password:
      label: master

