server:
  port: 7001

spring:
  application:
    name: eureka-cluster

eureka:
  instance: #eureka实例定义
    hostname: peer1 # 定义eureka所在的主机名称
  client:
    fetch-registry: false # 是否从eureka拉取注册信息，默认为true
    register-with-eureka: false # 是否将自己注册到Eureka Service，默认为true
    service-url:
      defaultZone: http://eureka2:7002/eureka,http://eureka3:7003/eureka