server:
  port: 7001

eureka:
  instance: #eureka实例定义
    hostname: eureka1 # 定义eureka所在的主机名称
  client:
    fetch-registry: false # 不需要从eureka拉取注册信息
    register-with-eureka: false # 不需要注册到eureka
    service-url:
      defaultZone: http://eureka1:7001/eureka
  server:
    eviction-interval-timer-in-ms: 1000 #设置清洗的间隔时间，时间使用的是毫秒单位（默认是60s）
    enable-self-preservation: false # 设置false表示关闭保护模式，（保护模式：有一段时间不可用还保留）